### PR TITLE
Added methods to start and clear force stop timeout

### PR DESCRIPTION
**Pull request by SlNPacifist**
`stopTimeout` parameter now uses `worker.process.kill()` to kill hung workers
`stopTimeout` time now starts counting from `restart()`, `stop()` calls or `disconnect` event, whichever happens first

### CODE REVIEW

**Comment by Flackus** [comment]
Agreed to add a functional test for this change.

**Comment by SlNPacifist** [comment]
I added two functional tests that spawn master + 1 worker and imitate two situations:
1) Worker hangs (infinite cycle) after receiving special signal. Master should be able to kill it with "restart"
2) Worker disconnects and hangs afterwards (it does not end its process), master should kill such a process after receiving 'disconnect' event and waiting for some time.

**Comment by kaero** [comment]
lgtm

**Comment by Flackus** [comment]
🆗

**Pull request merged**
