### PR TITLE
Remade most of examples as functional tests

### PR DESCRIPTION
**Pull request by SlNPacifist**
Moved "manual_ready" example to functional test
Moved "override_config" example to functional test
Moved "master_to_workers_event" example to "emit_to_all" functional test
Moved "remote_command_with_callback" example to "remote_call_on_master", "remote_call_on_worker" functional tests
Duplicated "simple_extension" example as "async_extension", "simple_extension" functional tests

### CODE REVIEW

**Comment by kaero** [comment]
lgtm

\cc @Flackus

**Comment by Flackus** [comment]
LGTM.
But two tests have the same output on test run: https://yadi.sk/i/jR_byy5R3ErdTh
That should be fixed.

**Comment by SlNPacifist** [comment]
Fixed

**Comment by Flackus** [comment]
Nice.

**Pull request merged**
